# Company
COMPANY = "Pracodawca"
COMPANIES = "Pracodawcy"
NIP = "NIP"
COMPANY_NAME = "Nazwa firmy"
EMAIL = "E-mail"
PHONE_NUMBER = "Numer telefonu"
LOCATION = "Lokalizacja"
WEBSITE = "Strona internetowa"
DESCRIPTION = "Opis"
IMAGE = "Zdjęcie"
USER = "Konto użytkownika"
AUTO_VERIFY = "Automatyczna weryfikacja"

# Candidate
CANDIDTE = "Kandydat"
CANDIDATES = "Kandydaci"
PESEL = "PESEL"
FIRST_NAME = "Imię"
LAST_NAME = "Nazwisko"
PHONE_NUMBER = "Numer telefonu"
LOCATION = "Lokalizacja"
IMAGE = "Zdjęcie"
USER = "Konto użytkownika"

# File
FILE_NAME = "Nazwa"
ADDED_AT = "Data dodania"
FILE_TYPE = "Rodzaj"
FILE = "Plik"
FILES = "Pliki"

# Experience
EXPERIENCE = "Doświadczenie"
EXPERIENCES = "Doświadczenie"
POSITION = "Stanowisko"
COMPANY_NAME = "Nazwa firmy"
LOCATION = "Lokalizacja"
START_DATE = "Data rozpoczęcia"
END_DATE = "Data zakończenia"
DUTIES = "Obowiązki"
CANDIDATE = "Kandydat"
REFERENCES = "Referencje"
IS_CURRENT = "Aktualna"

# Education
EDUCATION = "Wykształcenie"
EDUCATIONS = "Wykształcenie"
INSTITUTE = "Uczelnia"
EDUCATION_LEVEL = "Poziom wykształcenia"
START_DATE = "Data rozpoczęcia"
END_DATE = "Data zakończenia"
MAJOR = "Kierunek"
CANDIDATE = "Kandydat"
DIPLOMA = "Dyplom"

# CSkill
SKILL = "Umiejętność"
SKILLS = "Umiejętności"
SKILL_TYPE = "Typ"
SKILL_NAME = "Nazwa"
LEVEL = "Poziom"
CERTIFICATE = "Certyfikat"

# Course
COURSE = "Kurs"
COURSES = "Kursy"
COURSE_NAME = "Nazwa"
DESCRIPTION = "Opis"
START_DATE = "Data rozpoczęcia"
END_DATE = "Data zakończenia"
CANDIDATE = "Kandydat"
CERTIFICATE = "Certyfikat"

# Link
LINK = "Link"
LINKS = "Linki"
LINK_TYPE = "Rodzaj"
URL = "Adres URL"
CANDIDATE = "Kandydat"
