export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST'
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS'
export const APPLICATION_LIST_FAIL = 'APPLICATION_LIST_FAIL'
export const APPLICATION_LIST_CLEAR = 'APPLICATION_LIST_CLEAR'

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST'
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS'
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL'
export const APPLICATION_DETAILS_CLEAR = 'APPLICATION_DETAILS_CLEAR'

export const APPLICATION_REQUEST = 'APPLICATION_REQUEST'
export const APPLICATION_SUCCESS = 'APPLICATION_SUCCESS'
export const APPLICATION_FAIL = 'APPLICATION_FAIL'
export const APPLICATION_RESET = 'APPLICATION_RESET'
