export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST';
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS';
export const APPLICATION_LIST_FAIL = 'APPLICATION_LIST_FAIL';
export const APPLICATION_LIST_CLEAR = 'APPLICATION_LIST_CLEAR';