export const CANDIDATE_COMPONENT_REQUEST = 'CANDIDATE_COMPONENT_REQUEST'
export const CANDIDATE_COMPONENT_SUCCESS = 'CANDIDATE_COMPONENT_SUCCESS'
export const CANDIDATE_COMPONENT_FAIL = 'CANDIDATE_COMPONENT_FAIL'
export const CANDIDATE_COMPONENT_RESET = 'CANDIDATE_COMPONENT_RESET'