export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST';
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS';
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL';
export const COMPANY_LIST_CLEAR = 'COMPANY_LIST_CLEAR';

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST';
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS';
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL';
export const COMPANY_DETAILS_CLEAR = 'COMPANY_DETAILS_CLEAR';
