export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST';
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS';
export const OFFER_LIST_FAIL = 'OFFER_LIST_FAIL';

export const OFFER_FILTERED_LIST_REQUEST = 'OFFER_FILTERED_LIST_REQUEST';
export const OFFER_FILTERED_LIST_SUCCESS = 'OFFER_FILTERED_LIST_SUCCESS';
export const OFFER_FILTERED_LIST_FAIL = 'OFFER_FILTERED_LIST_FAIL';
export const OFFER_FILTERED_LIST_CLEAR = 'OFFER_FILTERED_LIST_CLEAR';

export const OFFER_DETAILS_REQUEST = 'OFFER_DETAILS_REQUEST';
export const OFFER_DETAILS_SUCCESS = 'OFFER_DETAILS_SUCCESS';
export const OFFER_DETAILS_FAIL = 'OFFER_DETAILS_FAIL';
export const OFFER_DETAILS_CLEAR = 'OFFER_DETAILS_CLEAR';

