export const SKILL_LIST_REQUEST = 'SKILL_LIST_REQUEST'
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS'
export const SKILL_LIST_FAIL = 'SKILL_LIST_FAIL'
export const SKILL_LIST_CLEAR = 'SKILL_LIST_CLEAR'