export const USER_DETAILS_PROFILE_REQUEST = 'USER_DETAILS_PROFILE_REQUEST'
export const USER_DETAILS_PROFILE_SUCCESS = 'USER_DETAILS_PROFILE_SUCCESS'
export const USER_DETAILS_PROFILE_FAIL = 'USER_DETAILS_PROFILE_FAIL'
export const USER_DETAILS_PROFILE_RESET = 'USER_DETAILS_PROFILE_RESET'

export const USER_CREATE_PROFILE_REQUEST = 'USER_CREATE_PROFILE_REQUEST'
export const USER_CREATE_PROFILE_SUCCESS = 'USER_CREATE_PROFILE_SUCCESS'
export const USER_CREATE_PROFILE_FAIL = 'USER_CREATE_PROFILE_FAIL'
export const USER_CREATE_PROFILE_RESET = 'USER_CREATE_PROFILE_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_DELETE_PROFILE_REQUEST = 'USER_DELETE_PROFILE_REQUEST'
export const USER_DELETE_PROFILE_SUCCESS = 'USER_DELETE_PROFILE_SUCCESS'
export const USER_DELETE_PROFILE_FAIL = 'USER_DELETE_PROFILE_FAIL'

export const USER_EDUCATION_REQUEST = 'USER_EDUCATION_REQUEST'
export const USER_EDUCATION_SUCCESS = 'USER_EDUCATION_SUCCESS'
export const USER_EDUCATION_FAIL = 'USER_EDUCATION_FAIL'
export const USER_EDUCATION_RESET = 'USER_EDUCATION_RESET'

export const USER_SKILL_REQUEST = 'USER_SKILL_REQUEST'
export const USER_SKILL_SUCCESS = 'USER_SKILL_SUCCESS'
export const USER_SKILL_FAIL = 'USER_SKILL_FAIL'
export const USER_SKILL_RESET = 'USER_SKILL_RESET'

export const USER_COURSE_REQUEST = 'USER_COURSE_REQUEST'
export const USER_COURSE_SUCCESS = 'USER_COURSE_SUCCESS'
export const USER_COURSE_FAIL = 'USER_COURSE_FAIL'
export const USER_COURSE_RESET = 'USER_COURSE_RESET'

export const USER_LINK_REQUEST = 'USER_LINK_REQUEST'
export const USER_LINK_SUCCESS = 'USER_LINK_SUCCESS'
export const USER_LINK_FAIL = 'USER_LINK_FAIL'
export const USER_LINK_RESET = 'USER_LINK_RESET'

export const USER_EXPERIENCE_REQUEST = 'USER_EXPERIENCE_REQUEST'
export const USER_EXPERIENCE_SUCCESS = 'USER_EXPERIENCE_SUCCESS'
export const USER_EXPERIENCE_FAIL = 'USER_EXPERIENCE_FAIL'
export const USER_EXPERIENCE_RESET = 'USER_EXPERIENCE_RESET'

export const USER_FILES_SUCCESS = 'USER_FILES_SUCCESS'
export const USER_FILES_FAIL = 'USER_FILES_FAIL'

